# Generated by Django 2.0.1 on 2018-11-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beastiary', '0002_auto_20181103_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='consequences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beastiary.Consequence'),
        ),
        migrations.AddField(
            model_name='npc',
            name='stress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beastiary.Stress'),
        ),
    ]
