# Generated by Django 2.0.1 on 2018-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beastiary', '0005_auto_20181110_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consequence',
            options={'ordering': ['name', 'placeholder']},
        ),
        migrations.RemoveField(
            model_name='consequence',
            name='slots',
        ),
        migrations.AddField(
            model_name='consequence',
            name='name',
            field=models.CharField(default='Mild (2)', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consequence',
            name='placeholder',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='npc',
            name='consequences',
        ),
        migrations.AddField(
            model_name='npc',
            name='consequences',
            field=models.ManyToManyField(blank=True, null=True, to='beastiary.Consequence'),
        ),
    ]
