# Generated by Django 2.0.1 on 2018-01-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180113_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='published_date',
        ),
    ]
