# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180113_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=b'media/'),
        ),
    ]
